export const SET_PLAYERS = "SET_PLAYERS";
export const SET_CURRENT_PLAYER_ID = "SET_CURRENT_PLAYER_ID";
export const GET_ALIVE_OPPONENTS = "GET_ALIVE_OPPONENTS";
export const GET_CONNECTED_PLAYER = "GET_CONNECTED_PLAYER";
export const GET_PLAYER_WHO_HAS_TO_PLAY = "GET_PLAYER_WHO_HAS_TO_PLAY";
